name: "Check Changelog"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "examples/demo-rollup/**/*.rs"
      - "examples/demo-rollup/**/*.toml"
      - "!examples/demo-rollup/sov-soak-testing/**"

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for demo-rollup changes requiring changelog
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | sed 's/.*\/pull\/\([0-9]*\).*/\1/')

          if !  grep -q "#${PR_NUMBER}" CHANGELOG.md; then
            echo "Error: Demo rollup was changed but no changelog entry found for PR #${PR_NUMBER}."
            echo "If you've already checked in a changelog entry, make sure it contains the literal string `#${PR_NUMBER}`."
            exit 1
          fi
