[package]
name = "sov-accounts"
description = "A Sovereign SDK module for managing rollup state using accounts"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
schemars = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }

sov-modules-api = { workspace = true }
sov-state = { workspace = true }

arbitrary = { workspace = true, optional = true }

[dev-dependencies]
sov-accounts = { path = ".", features = ["native"] }
tempfile = { workspace = true }
strum = { workspace = true }
sov-modules-api = { workspace = true, features = ["test-utils"] }
sov-test-utils = { workspace = true }

[features]
default = []
arbitrary = [
	"dep:arbitrary",
	"sov-accounts/arbitrary",
	"sov-modules-api/arbitrary",
	"sov-state/arbitrary",
	"sov-test-utils/arbitrary",
]
native = [
	"sov-accounts/native",
	"sov-modules-api/native",
	"sov-state/native",
]
test-utils = []
