[package]
name = "sov-aggregated-proof"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0 = { path = "methods" }
hex = "0.4"
anyhow = { version = "1.0.95" }
risc0-zkvm = { version = "1.2" }
risc0-zkp = "1.2"
borsh = { version = "1", features = ["derive"] }


sov-mock-da = { workspace = true }
sov-state = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-modules-api = { workspace = true }

sov-risc0-adapter = { workspace = true }
sov-mock-zkvm = { workspace = true }


[features]
default = []
prove = ["risc0-zkvm/prove"]
