# Rename this file and move it into workflows/ to reactivate dependency review.

name: "Dependency Review"
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: nscloud-ubuntu-22.04-amd64-2x4
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: critical
