[package]
name = "sov-soak-testing"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
publish = false
default-run = "main"

[dependencies]
tokio = { version = "1.42", default-features = false }
borsh = { workspace = true, features = ["derive"] }

schemars = { version = "0.8.21", features = ["derive"] }
serde = { version = "1.0.208", default-features = false, features = [
    "alloc",
    "derive",
] }
anyhow = { workspace = true }
derivative = { version = "2.2", features = ["use_core"] }
strum = { version = "0.26.3", features = ["derive"] }
rand = "0.8"
clap = { version = "4", features = ["derive"] }
reqwest = { workspace = true }

sov-api-spec = { path = "../../../crates/full-node/sov-api-spec" }
sov-metrics = { path = "../../../crates/full-node/sov-metrics" }
sov-modules-rollup-blueprint = { path = "../../../crates/module-system/sov-modules-rollup-blueprint" }
sov-transaction-generator = { path = "../../../crates/utils/transaction-generator" }
sov-modules-api = { path = "../../../crates/module-system/sov-modules-api" }
sov-test-utils = { path = "../../../crates/module-system/sov-test-utils", features = [
    "arbitrary",
] }
sov-mock-da = { path = "../../../crates/adapters/mock-da", features = [
    "arbitrary",
    "native",
] }
sov-mock-zkvm = { path = "../../../crates/adapters/mock-zkvm", features = [
    "native",
] }
sov-rollup-interface = { path = "../../../crates/rollup-interface", features = [
    "arbitrary",
] }
sov-node-client = { path = "../../../crates/utils/sov-node-client" }
sov-sequencer = { path = "../../../crates/full-node/sov-sequencer", default-features = false }
sov-kernels = { path = "../../../crates/module-system/sov-kernels", features = [
    "native",
] }
sov-state = { path = "../../../crates/module-system/sov-state", features = [
    "arbitrary",
] }
# modules
sov-value-setter = { path = "../../../crates/module-system/module-implementations/sov-value-setter" }
sov-bank = { path = "../../../crates/module-system/module-implementations/sov-bank/", features = [
    "native",
    "arbitrary",
] }
sov-paymaster = { path = "../../../crates/module-system/module-implementations/sov-paymaster", features = [
    "native",
] }
sov-celestia-adapter = { workspace = true, features = ["native", "arbitrary"] }
sov-address = { workspace = true }
demo-stf = { path = "../stf", features = ["native"] }

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "generator"
path = "src/bin/generator.rs"
