[package]
name = "sov-metrics"
authors = { workspace = true }
description = "Metrics tracking and publishing for Sovereign rollups"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
readme = "./README.md"

[lints]
workspace = true

[dependencies]
tracing = { workspace = true, optional = true }
strum = { workspace = true, optional = true }
tokio = { workspace = true, features = ["sync", "net", "macros", "rt", "io-util"], default-features = false, optional = true }
serde = { workspace = true }
bincode = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
http = { version = "1.0", optional = true }
derivative = { workspace = true, optional = true }
sov-rollup-interface = { workspace = true }
derive_more = { workspace = true, features = ["deref_mut", "deref"], optional = true }

anyhow = { workspace = true }
risc0-zkvm = { workspace = true, default-features = false, features = [
    "std",
], optional = true }
risc0-zkvm-platform = { workspace = true, features = ["export-syscalls"], optional = true }
sp1-lib = { version = "3.0", default-features = false, optional = true }

chrono = { workspace = true, optional = true }

[dev-dependencies]
sov-metrics = { path = ".", features = ["native"] }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
insta = { workspace = true }
toml = { workspace = true }

[features]
default = []
gas-constant-estimation = ["chrono"]
risc0 = [
    "dep:risc0-zkvm",
    "dep:risc0-zkvm-platform",
    "dep:bincode",
    "sov-metrics/risc0"
]
sp1 = ["dep:sp1-lib", "dep:bincode"]
native = [
    "dep:tokio",
    "dep:schemars",
    "dep:tracing",
    "dep:strum",
    "dep:bincode",
    "dep:http",
    "dep:derivative",
    "dep:schemars",
    "dep:derive_more",
    "dep:derivative",
    "sov-rollup-interface/native",
    "sov-metrics/native"
]
