[package]
name = "proof-aggregation"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2", features = ["std"], default-features = false }
risc0-zkp = "1.2"
hex = "0.4"


sov-mock-da = { path = "../../../../adapters/mock-da" }
sov-state = { path = "../../../../module-system/sov-state" }
sov-rollup-interface = { path = "../../../../rollup-interface" }
sov-modules-api = {path = "../../../../module-system/sov-modules-api"}

sov-risc0-adapter = { path = "../../../../adapters/risc0" }
sov-mock-zkvm = { path = "../../../../adapters/mock-zkvm"} 


[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
# Corresponding release: <https://github.com/risc0/curve25519-dalek/releases/tag/curve25519-4.1.2-risczero.0>
ed25519-dalek = { git = "https://github.com/risc0/curve25519-dalek", rev = "3dccc5b71b806f500e73829e2a5cbfe288cce2a0" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }

