[package]
name = "sp1"
version = "0.3.0"
edition = "2021"
resolver = "2"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
lazy_static = { workspace = true }

[lints]
workspace = true

[build-dependencies]
# External dependencies from crates.io
sp1-build = { version = "4.0.0", default-features = false }

[features]
bench = []
