[toolchain]
anchor_version = "0.30.1-db6da5c67d896e0a94c158f69e9b235e364b3064"
solana_version = "2.0.5"

[features]
resolution = true
skip-lint = false

[programs.localnet]
proxy = "3ATxf2BgWJ1SvMvtz3sZJWfVMnFzZvtXyLZ5Shh6UnnA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "cargo nextest run"
