[package]
name = "sov-blob-sender"
authors = { workspace = true }
description = "A blob submission manager for Sovereign rollup nodes"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
derive_more = { workspace = true }
futures = { workspace = true }
rockbound = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sov-rollup-interface = { workspace = true, features = ["native"]  }
sov-metrics = { workspace = true, features = ["native"] }
sov-modules-api = { workspace = true, features = ["native"] }
sov-db = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v7"] }

[dev-dependencies]
sov-mock-da = { workspace = true, features = ["native"] }
tempfile = { workspace = true }