[package]
name = "demo-stf"
version = "0.3.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
alloy-chains = "=0.1.27"
alloy-primitives = "=0.7.7"
strum = { workspace = true, features = ["derive"] }
schemars = { workspace = true }

sov-accounts = { workspace = true }
sov-address = { workspace = true, features = ["evm"] }
sov-attester-incentives = { workspace = true }
sov-bank = { workspace = true }
sov-capabilities = { workspace = true }
sov-chain-state = { workspace = true }
sov-blob-storage = { workspace = true }
sov-evm = { workspace = true }
sov-modules-api = { workspace = true }
sov-modules-stf-blueprint = { workspace = true }
sov-uniqueness = { workspace = true }
sov-paymaster = { workspace = true }
sov-prover-incentives = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-sequencer-registry = { workspace = true }
sov-state = { workspace = true }
sov-value-setter = { workspace = true }
sov-kernels = { workspace = true }
sov-rollup-apis = { workspace = true, optional = true }
sov-test-modules = { workspace = true }
sov-test-utils = { workspace = true, optional = true }


[features]
default = []
native = [
    "sov-accounts/native",
    "sov-attester-incentives/native",
    "sov-bank/native",
    "sov-capabilities/native",
    "sov-chain-state/native",
    "sov-evm/native",
    "sov-kernels/native",
    "sov-modules-api/native",
    "sov-modules-stf-blueprint/native",
    "sov-uniqueness/native",
    "sov-prover-incentives/native",
    "sov-rollup-interface/native",
    "sov-sequencer-registry/native",
    "sov-state/native",
    "sov-value-setter/native",
    "sov-blob-storage/native",
    "sov-rollup-apis",
    "sov-paymaster/native",
    "sov-address/native",
    "sov-test-modules/native"
]

# We only activate test-utils if we also have native since all our test-code use native by default.
test-utils = [
    "native",
    "sov-test-utils",
]
