[package]
name = "sov-node-client"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }

sov-api-spec = { workspace = true }
sov-bank = { workspace = true, features = ["native"] }
sov-sequencer-registry = { workspace = true, features = ["native"] }
sov-rollup-interface = { workspace = true, features = ["native"] }
sov-modules-api = { workspace = true, features = ["native"] }
tracing = { workspace = true }

[lints]
workspace = true
