[package]
name = "sov-paymaster"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
borsh = { workspace = true, features = ["rc"] }
bcs = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
schemars = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

sov-bank = { workspace = true }
sov-state = { workspace = true }
sov-modules-api = { workspace = true }
sov-universal-wallet = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
sov-paymaster = { path = ".", version = "*", features = ["native"] }
sov-test-utils = { workspace = true }
sov-state = { workspace = true, features = ["native"] }
sov-kernels = { workspace = true, features = ["native"] }
strum = { workspace = true }

[features]
native = [
	"sov-paymaster/native",
	"sov-bank/native",
	"sov-modules-api/native",
	"sov-state/native",
	"sov-kernels/native",
]
default = []
arbitrary = [
	"dep:arbitrary",
	"dep:proptest",
	"dep:proptest-derive",
	"sov-paymaster/arbitrary",
	"sov-modules-api/arbitrary",
	"sov-state/arbitrary",
	"sov-test-utils/arbitrary",
	"sov-bank/arbitrary",
]
