[package]
name = "sov-value-setter"
description = "A Sovereign SDK example module for setting/reading value from state"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = false

[lints]
workspace = true

[dev-dependencies]
sov-address = { workspace = true }
tempfile = { workspace = true }
strum = { workspace = true }
sov-value-setter = { workspace = true, features = ["native"] }
sov-modules-api = { workspace = true, features = ["native"] }
sov-test-utils = { workspace = true }
sov-state = { workspace = true, features = ["native"] }

[dependencies]
anyhow = { workspace = true }
strum = { workspace = true }
sov-modules-api = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
sov-state = { workspace = true }

[features]
default = []
native = [
	"sov-modules-api/native",
	"sov-value-setter/native",
	"sov-state/native",
	"sov-address/native"
]
