name: Set up ZKVM toolchains and Rust
description: Set up ZKVM toolchains and Rust
inputs:
  github_token:
    description: "Token to use for private repo access"
    required: true
  # Useful if the job e.g. uses `SKIP_GUEST_BUILD` or `SP1_SKIP_PROGRAM_BUILD`.
  # Saves some installation time.
  install_zkvm:
    description: "Install the ZKVM toolchain(s)"
    required: false
    default: "1"
runs:
  using: "composite"
  steps:
    # Install Rust
    - name: Install Rust
      shell: bash
      # Hack: rustup show installs Rust from `rust-toolchain.toml`.
      # See <https://github.com/rust-lang/rustup/issues/3635>.
      run: rustup show && rustup toolchain install nightly --component rustfmt --profile minimal
    # Install ZKVM toolchains
    - name: Install cargo-risczero toolchain
      uses: taiki-e/install-action@v2
      if: ${{ inputs.install_zkvm == '1' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tool: cargo-risczero@1.0
    - name: Install risc0-zkvm toolchain # Use the risc0 cargo extension to install the risc0 std library for the current toolchain
      shell: bash
      if: ${{ inputs.install_zkvm == '1' }}
      run: make install-risc0-toolchain
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Install SP1 toolchain
      shell: bash
      if: ${{ inputs.install_zkvm == '1' }}
      env:
        SHELL: /bin/bash
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: make install-sp1-toolchain
    # Other tools and dependencies
    - uses: rui314/setup-mold@v1
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "23.2"
        repo-token: ${{ inputs.github_token }}
    - uses: taiki-e/install-action@cargo-hack
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - uses: taiki-e/install-action@nextest
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - uses: taiki-e/install-action@cargo-llvm-cov
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - uses: taiki-e/install-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tool: zepter@1
    - name: Install Bashtestmd
      uses: taiki-e/install-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tool: bashtestmd@0.5
    # CI always operates on the entire workspace
    - run: cargo switcheroo disable
      shell: bash
