[package]
name = "sov-rollup-apis"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = true

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
borsh = { workspace = true }
derive_more = { workspace = true }
derivative = { workspace = true }
serde = { workspace = true }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
openapiv3 = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["base64"] }
serde_yaml = { workspace = true }
base64 = { workspace = true }

# Sovereign dependencies
sov-rest-utils = { workspace = true }
sov-modules-api = { workspace = true, features = ["native"] }
sov-modules-stf-blueprint = { workspace = true, features = ["native"] }
sov-api-spec = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-uniqueness = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
axum-server = { workspace = true }
anyhow = { workspace = true }
strum = { workspace = true }

# Sovereign dependencies
sov-bank = { workspace = true, features = ["native"] }
sov-test-utils = { workspace = true }
sov-kernels = { workspace = true, features = ["native"] }
sov-state = { workspace = true, features = ["native"] }

