[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "MIT-0",
    "NCSA",
    "Unlicense",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "MPL-2.0",
    "ISC",
    "CC0-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "OpenSSL",
    "Apache-2.0 WITH LLVM-exception",
    "Zlib",
    "BSL-1.0", # Relevant discussion: <https://github.com/Sovereign-Labs/sovereign-sdk-wip/pull/985#issuecomment-2242712349>.
]

[[licenses.clarify]]
name = "ring"
# ring is derived from BoringSSL and has a bit of a special licensing situation,
# but we can effectively treat is as OpenSSL-like licensing.
expression = "OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[[licenses.clarify]]
# Halo 2 is now MIT licensed, but the update hasn't been published on crates.io
# Its resolved license is BOSL, which is effectively proprietary.
name = "halo2"
expression = "LicenseRef-Proprietary"
license-files = [{ path = "COPYING", hash = 0x106164e0 }]


[[licenses.exceptions]]
allow = ["LGPL-3.0"]
# Used by `risc0-circuit-recursion` in its build script: <https://github.com/risc0/risc0/blob/3177cdedda8fad56d7acd71fe2439e8dd0d93413/risc0/circuit/recursion/build.rs>.
name = "downloader"
version = "0.2"

[[licenses.exceptions]]
# Halo 2 is now MIT licensed, but the update hasn't been published on crates.io
allow = ["LicenseRef-Proprietary"]
name = "halo2"
version = "0.1.0-beta.2"

[sources]
# We're okay with sourcing crates from Git repositories.
unknown-git = "allow"
# If we source crates from Git repositories, we always ought to pin them by
# commit. If we don't, we effectively allow maintainers to inject arbitrary code
# into our dependency tree just by e.g. overwriting a tag.
required-git-spec = "rev" 

[bans]
# We have so many duplicates, that warnings are barely useful. (I know, not a fan of this.)
# TODO: See <https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/1016>.
multiple-versions = "allow" 
# We'd prefer to use Rustls instead of OpenSSL; this helps up from accidentally
# using OpenSSL. See <https://github.com/Sovereign-Labs/sovereign-sdk-wip/issues/352>.
deny = [{ name = "native-tls" }, { name = "openssl" }]
